name: Events Demo 1
on: 
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
    deploy: 
        runs-on: ubuntu-latest
        steps:
           - name: Echo basic event details
             run: |
               echo "Event name: ${{ toJson(github.event) }}"
           - name: check is triggere or not
             run: echo "event triggere on pull request"
        

